READY_PREFIX = "ready_"

DOMAIN_A_FOLDER = "cartoonset10k"
DOMAIN_B_FOLDER = "celeba"

DOMAIN_A_FILES = f"{DOMAIN_A_FOLDER}/*.png"
DOMAIN_A_READY = f"{READY_PREFIX}{DOMAIN_A_FOLDER}"
DOMAIN_A_READY_FILES = f"{DOMAIN_A_READY}/*.png"

DOMAIN_B_FILES = f"{DOMAIN_B_FOLDER}/*.jpg"
DOMAIN_B_READY = f"{READY_PREFIX}{DOMAIN_B_FOLDER}"
DOMAIN_B_READY_FILES = f"{DOMAIN_B_READY}/*.jpg"

MODEL_INPUT_SIZE = 128
